import os
import subprocess
import tempfile
import configparser
from pathlib import Path

# Graph for Exporting to SNAPHU format
SNAP_EXPORT_GRAPH = """<graph id="SnaphuExport">
  <version>1.0</version>
  <node id="Read">
    <operator>Read</operator>
    <sources/>
    <parameters><file>${input_dimap}</file></parameters>
  </node>
  <node id="SnaphuExport">
    <operator>SnaphuExport</operator>
    <sources><sourceProduct refid="Read"/></sources>
    <parameters>
      <targetFolder>${export_dir}</targetFolder>
      <statCostMode>DEFO</statCostMode>
      <initMethod>MCF</initMethod>
      <numberOfTileRows>4</numberOfTileRows>
      <numberOfTileCols>4</numberOfTileCols>
      <numberOfProcessors>4</numberOfProcessors>
      <rowOverlap>100</rowOverlap>
      <colOverlap>100</colOverlap>
      <tileCostThreshold>500</tileCostThreshold>
    </parameters>
  </node>
</graph>
"""

# Graph for Importing the unwrapped phase back into SNAP
SNAP_IMPORT_GRAPH = """<graph id="SnaphuImport">
  <version>1.0</version>
  <node id="Read-Phase">
    <operator>Read</operator>
    <sources/>
    <parameters><file>${wrapped_dimap}</file></parameters>
  </node>
  <node id="Read-Unwrapped">
    <operator>Read</operator>
    <sources/>
    <parameters><file>${unwrapped_hdr}</file></parameters>
  </node>
  <node id="SnaphuImport">
    <operator>SnaphuImport</operator>
    <sources>
      <sourceProduct refid="Read-Phase"/>
      <sourceProduct.1 refid="Read-Unwrapped"/>
    </sources>
    <parameters>
      <doNotKeepMergedBands>false</doNotKeepMergedBands>
    </parameters>
  </node>
  <node id="Write">
    <operator>Write</operator>
    <sources><sourceProduct refid="SnaphuImport"/></sources>
    <parameters>
      <file>${output_dimap}</file>
      <formatName>BEAM-DIMAP</formatName>
    </parameters>
  </node>
</graph>
"""

def unwrap_phase(interferogram_dimap: str, output_unwrapped_dimap: str, snaphu_path: str = "snaphu", gpt_path: str = "gpt"):
    """
    Exports the interferogram, runs SNAPHU phase unwrapping, and imports back into SNAP.
    """
    export_dir = tempfile.mkdtemp(prefix="snaphu_export_")
    
    try:
        # Step 1: Export to SNAPHU format
        print("Exporting interferogram for SNAPHU...")
        with tempfile.NamedTemporaryFile(mode='w', suffix='.xml', delete=False) as temp_export:
            temp_export.write(SNAP_EXPORT_GRAPH)
            export_graph = temp_export.name
            
        subprocess.run([
            gpt_path, export_graph,
            f"-Pinput_dimap={interferogram_dimap}",
            f"-Pexport_dir={export_dir}"
        ], check=True)
        os.remove(export_graph)
        
        # Locate the snaphu.conf file generated by SNAP
        conf_file = None
        for file in os.listdir(export_dir):
            if file.endswith(".conf"):
                conf_file = os.path.join(export_dir, file)
                break
                
        if not conf_file:
            raise RuntimeError("Snaphu configuration file not found in export directory")
            
        # Extract the unwrapped file name from the snaphu.conf
        unwrapped_hdr = None
        with open(conf_file, 'r') as f:
            for line in f:
                if line.startswith("OUTFILE"):
                    out_img = line.split()[1]
                    unwrapped_hdr = out_img.replace(".img", ".hdr")
                    break

        # Step 2: Run SNAPHU
        print(f"Running SNAPHU unwrapping (this may take a long time)...")
        # Run snaphu inside the export directory
        subprocess.run([snaphu_path, "-f", os.path.basename(conf_file)], cwd=export_dir, check=True)
        
        # Step 3: Import back into SNAP
        print("Importing unwrapped phase back into SNAP...")
        unwrapped_hdr_path = os.path.join(export_dir, unwrapped_hdr)
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.xml', delete=False) as temp_import:
            temp_import.write(SNAP_IMPORT_GRAPH)
            import_graph = temp_import.name
            
        subprocess.run([
            gpt_path, import_graph,
            f"-Pwrapped_dimap={interferogram_dimap}",
            f"-Punwrapped_hdr={unwrapped_hdr_path}",
            f"-Poutput_dimap={output_unwrapped_dimap}"
        ], check=True)
        os.remove(import_graph)
        
        print(f"Unwrapped interferogram saved to {output_unwrapped_dimap}")
        return output_unwrapped_dimap
        
    finally:
        # Cleanup intermediate SNAPHU files
        import shutil
        shutil.rmtree(export_dir, ignore_errors=True)
